server:
  port: 8091

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

spring:
  # 数据库配置；启动时配置数据库资源信息
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost:3306/groupbuy-market-plus?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource
  # RabbitMQ 配置
  rabbitmq:
    addresses:
    port:
    username:
    password:
    listener:
      simple:
        prefetch: 10 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    # 自定义消息配置
    config:
      # 生产者
      producer:
        # 绑定交换机
        exchange: groupbuy_market_plus_exchange
        # 消息主题配置 - 可能有多个主题需要配置，在这里做区分
        topic_team_success:
          # 消息主题
          routing_key: topic.team_success
          # 消费队列
          queue: groupbuy_market_plus_topic_team_success_queue

        topic_order_refund:
          routing_key: topic.order_refund
          queue: groupbuy_market_plus_topic_order_refund_queue

        topic_header_refund:
          routing_key: topic.header_refund
          queue: groupbuy_market_plus_topic_header_refund_queue

# MyBatis 配置
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Redis 配置
redis:
  sdk:
    config:
      host:
      port:
      password:
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml